name: Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (코드 체크아웃)
        uses: actions/checkout@v4

      - name: Set up JDK 21 (JDK 설정)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set environment variables
        run: |
          echo "SPRING_PROFILES_ACTIVE=local" >> $GITHUB_ENV
          echo "SECURITY_DEFAULT_USER=${{ secrets.SECURITY_DEFAULT_USER }}" >> $GITHUB_ENV
          echo "SECURITY_DEFAULT_PASS=${{ secrets.SECURITY_DEFAULT_PASS }}" >> $GITHUB_ENV
          echo "JWT_ISSUER=${{ secrets.JWT_ISSUER }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}" >> $GITHUB_ENV
          echo "ALLOWED_METHODS=${{ secrets.ALLOWED_METHODS }}" >> $GITHUB_ENV
          echo "ALLOW_CREDENTIALS=${{ secrets.ALLOW_CREDENTIALS }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DOMAIN }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> $GITHUB_ENV

      - name: Grant execute permission for Gradle (Gradle 빌드 및 테스트)
        run: |
          chmod +x gradlew
          ./gradlew test

  notify-jenkins:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Jenkins에 배포 요청
        run: |
          CRUMB=$(curl -u "blws:${{ secrets.JENKINS_API_TOKEN }}" -s "${{ secrets.JENKINS_CRUMB_URL }}" | jq -r '.crumb')
          curl -X POST -u "blws:${{ secrets.JENKINS_API_TOKEN }}" -H "Jenkins-Crumb:$CRUMB" "${{ secrets.JENKINS_WEBHOOK_URL }}"
